Search.web
infoshareacademy/jcszr8-Gity pull request #71
Opened 2023-03-14 17:48 UTC by PatrykWiacek

2023-03-15 15:06 UTC, janek2j commented
Ale tu jest pełno konfliktów z dev'em ...

2023-03-16 19:33 UTC, jacekpardel approved these changes
Fajnie wyglądajcy widok wyszukiwania

2023-03-16 23:32 UTC, janek2j requested changes

2023-03-16 23:32 UTC, janek2j commented on CarRental/CarRental.Logic/Interfaces/ISearchService.cs
> +using System;
Niepotrzebne using'i można usunąć (Ctrl + R G)

2023-03-16 23:32 UTC, janek2j commented on CarRental/CarRental.Logic/Interfaces/ISearchService.cs
> +namespace CarRental.Logic.Interfaces
W projekcie używamy namespace na poziomie pliku (czyli zakończone średnikiem i bez klamer)

2023-03-16 23:32 UTC, janek2j commented on CarRental/CarRental.Logic/SearchViewModelDto.cs
> +﻿using CarRental.DAL;
j.w. i podobnie w innych plikach

2023-03-16 23:32 UTC, janek2j commented on CarRental/CarRental.Logic/SearchViewModelDto.cs
> +    public class SearchViewModelDto
Jak już ktoś nam mówił to powino być ew. SearchViewModel bez Dto bo to jest niepotrzebne powtórzenie (tzn. view model = dto)

2023-03-16 23:32 UTC, janek2j commented on CarRental/CarRental.Logic/SearchViewModelDto.cs
> +        public Dictionary<string, bool> PremadeDic()
wg Clean Code nazwy powinny być czytelniejsze, np. PremadeDictionary zamiast tylko króko Dic na końcu

2023-03-16 23:32 UTC, janek2j commented on CarRental/CarRental.Logic/SearchViewModelDto.cs
> +        public Dictionary<string, bool> Makes { get; set; }
Dlaczego użyłeś tu słownika, zamiast jakiejś innej konstrukcji ?

2023-03-16 23:32 UTC, janek2j commented on CarRental/CarRental.Logic/Services/SearchService.cs
> +        public List<Car> SearchList(SearchViewModelDto search)
Nazwa zmiennej bardziej pasowałaby dla metody bo mówi o czynności,,
lepiej byłoby może searchModel lub coś podobnego

2023-03-16 23:32 UTC, janek2j commented on CarRental/CarRental.Logic/Services/SearchService.cs
> +            IEnumerable<int> getCarId = _rentalService.GetAvailableCarIds(search.StartDate, search.EndDate);
Nazwa zmiennej bardziej pasowałaby dla metody bo mówi o czynności,,
lepiej byłoby chyba np. carIds

2023-03-16 23:32 UTC, janek2j commented on CarRental/CarRental.Web/Models/CarListModel.cs
> +    public CarListModel FillModel(Car baseModel)
To chyba sam nieszczęśliwie nadałem nazwą CarListModel, lepsze byłoby CarViewModel 
(poprawka może być ew. przy refactoringu)

2023-03-17 18:11 UTC, PatrykWiacek commented on CarRental/CarRental.Logic/SearchViewModelDto.cs
> +        public Dictionary<string, bool> Makes { get; set; }
poniewaz na stronie wykorzystywane sa checkboxy i one wymagaja dictionary

2023-03-18 12:27 UTC, jacekpardel approved these changes
Przetestowane - działa

2023-03-19 16:37 UTC, janek2j approved these changes
Mechanika wyszukiwania działa.

2023-03-19 16:50 UTC, merged