Jp new name label
infoshareacademy/jcszr8-Gity pull request #95
Opened 2023-04-25 19:29 UTC by jacekpardel

2023-04-25 20:09 UTC, janek2j requested changes
Jeszcze zapomniałeś o adnotacjach w RentalViewModel.cs

2023-04-25 20:09 UTC, janek2j commented on CarRental/CarRental.Web/Views/Rental/Details.cshtml
> +    }
to tak jak widzieliśmy :)

2023-04-25 20:09 UTC, janek2j commented on CarRental/CarRental.Web/Views/Shared/_Layout.cshtml
> +            &copy; 2023 - CarRental.Web -
dobrze byłoby to wycentrować

2023-04-26 13:34 UTC, janek2j requested changes

2023-04-26 13:34 UTC, janek2j commented on CarRental/CarRental.Logic/Models/CarViewModel.cs
> +    [Display(Name = "Year Of Production")]
może jednak lepiej będzie Production Year ?

2023-04-26 13:34 UTC, janek2j commented on CarRental/CarRental.Logic/Models/RentalViewModel.cs
> +    [Display(Name = "Customer ID")]
Id - używamy takiej konwencji

2023-04-26 13:34 UTC, janek2j commented on CarRental/CarRental.Logic/Models/RentalViewModel.cs
> +    [Display(Name = "Car ID")]
Id

2023-04-26 19:32 UTC, jacekpardel commented on CarRental/CarRental.Web/Views/Rental/Details.cshtml
> +    }
Usunięte

2023-04-26 19:32 UTC, jacekpardel commented on CarRental/CarRental.Web/Views/Shared/_Layout.cshtml
> +            &copy; 2023 - CarRental.Web -
Dodałem jeszcze jednego diva do centrowania tekstu - jest ok.

2023-04-26 19:33 UTC, jacekpardel commented on CarRental/CarRental.Logic/Models/RentalViewModel.cs
> +    [Display(Name = "Customer ID")]
Zmieniłem zgodnie z sugestią

2023-04-26 19:33 UTC, jacekpardel commented on CarRental/CarRental.Logic/Models/RentalViewModel.cs
> +    [Display(Name = "Car ID")]
Done

2023-04-26 19:43 UTC, janek2j commented on CarRental/CarRental.Web/Views/Shared/_Layout.cshtml
> +            &copy; 2023 - CarRental.Web</div>
niestety tekst stopki jest praktycznie niewidoczny na stronie

2023-04-26 19:56 UTC, janek2j approved these changes
wygląda dobrze

2023-04-26 20:23 UTC, PatrykWiacek approved these changes
git

2023-04-26 20:23 UTC, janek2j requested changes
w Rental Delete jest niestety nadal zły format daty, ale to już może przy okazji kolejnego PR

2023-04-26 20:26 UTC, janek2j approved these changes

2023-04-26 20:26 UTC, merged